version: "2"
services:
  api.noahjahn.dev:
    image: "node:14-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "8000:8000"
    command: /bin/ash -c "npm install && npm run dev:start"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: api-noahjahn-dev
      MONGO_INITDB_ROOT_USERNAME: apinoahjahndev
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: