name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm install

  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          rsync -r --copy-links --verbose $GITHUB_WORKSPACE /home/github-runner/apps
          pm2 reload /home/github-runner/apps/api.noahjahn.dev/ecosystem.config.js --only api.noahjahn.dev
