name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
          /usr/bin/rysnc $GITHUB_WORKSPACE ~/sites/api.noahjahn.dev
