name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - run: |
          rsync -r --copy-links --verbose $GITHUB_WORKSPACE /home/pi/sites
